### ISSUE TITLE
Web UI missing components?

### ISSUE THREAD

**Issue by nfaggian** [dask/distributed#227]
When trying out the UI for the first time today I get a figure without two of the components - for example:

![image](https://cloud.githubusercontent.com/assets/377869/14552239/a093457c-031f-11e6-9583-2fe0450f0c18.png)

Using chrome version 49.0.2623.87 (64-bit)

**Comment by mrocklin** [comment]
Are there any errors coming from the scheduler logs?

**Comment by mrocklin** [comment]
Or errors coming from the browser I suppose.  In chrome the development console is available by hitting F12

**Comment by nfaggian** [comment]
No errors in logs. I am using the imperative interface to form a graph if that helps..

**Comment by mrocklin** [comment]
The scheduler doesn't know/care how the graph was formed (it's all the same soup at that stage).  

One similarity between the missing graphs is that both connect to the scheduler over TCP at the address `localhost:8786`.  This is incorrect if the scheduler runs on a different port.  We should make these programmable.  Is this possibly an issue for you?

**Comment by nfaggian** [comment]
I will check it out. I am using docker to setup a scheduler and pin down ports. It's possible I am goofing. Generally I think it's good to be able to pin all ports. One thing I ran into was a white list problem for bokeh... it made my docker-compose script a bit of a drag when my scheduler was on a remote host I had to explicitly list that hostname in the scheduler command.

**Comment by nfaggian** [comment]
Do you think it might be a good idea to have a configuration file for the scheduler?

**Comment by mrocklin** [comment]
I agree about the bokeh whitelist.  This will be fixed in the next release of Bokeh. See https://github.com/bokeh/bokeh/pull/4052

I think that a configuration file for the scheduler sounds like a very fine idea.  It would be good to get your thoughts on what you would find valuable.

**Comment by nfaggian** [comment]
I think it might be good to initially pull all the command line args into config.

**Comment by nfaggian** [comment]
OK - I think the use of localhost might be an issue for schedulers running in containers. Seems to be a world of pain associated with mapping things appropriately.

**Comment by nfaggian** [comment]
If you specify a "host" argument then perhaps you should use that instead of localhost?

**Comment by mrocklin** [comment]
Yes, that seems quite sensible.  So does making it accessible from the command line.  It might be a bit tricky to pass things down to the bokeh server.  I'll have time to look into things more deeply tomorrow.

**Comment by nfaggian** [comment]
Thanks Matthew -- cannot emphasize enough how useful this work is. Please keep the momentum up!

**Comment by mrocklin** [comment]
OK, so it looks like Bokeh does allow you to pass keyword arguments down to Bokeh server applications (see https://github.com/bokeh/bokeh/pull/4010/files#diff-2295c07d712da9ccef87a86e3e955672R53) but this isn't yet in a release.  Looking around for alternatives.

@nfaggian are you able to test a couple things on your setup?  I'm curious if using `127.0.0.1` in place of `localhost` is more robust for docker setups.

**Comment by mrocklin** [comment]
Actually, I'm reproducing this locally.  Bisecting down to commit that causes the failure doesn't clarify why it's happening.  However @nfaggian you might want to try installing from `487ee78cabad4cd4eede4174ffc3214a64e01b5f` which seems to run well, at least on my machine.

**Comment by mrocklin** [comment]
OK, this appears to be a spawn vs fork issue.  I can resolve it easily in Python 3, hunting around for a Python 2 solution.

**Comment by mrocklin** [comment]
I believe that this is resolved by #233 .  Please let me know if this is not the case.  I can also add Bokeh server options fairly easily if desired but I'd prefer to wait until next Bokeh release (about a month) if there is no immediate need.

**Comment by nfaggian** [comment]
Hi - I still see the issue. But I believe it might be a docker problem, should be easy to replicate in any container. If the host was explicitly defined maybe that would help.

**Comment by mrocklin** [comment]
Alrighty.  Will do.

**Comment by nfaggian** [comment]
No change with the JSON files.

----------------------------------------------------------------------------

Nathan Faggian,  Ph.D.

Phone   :  0416 030 253
Email   :  nathan.faggian@gmail.com

----------------------------------------------------------------------------

**Comment by mrocklin** [comment]
This should allow you to tweak host settings.

If that's not the issue and the previous problem solved in #233 isn't the problem (which surprises me as I was able to reproduce and then solve things) then we're back to the drawing board.

Any other thoughts or information?  Anything coming out of the scheduler's logs or the develop console in the browser? (F12 in chrome)

**Comment by nfaggian** [comment]
Hi - I will see if I can get any further with tests - otherwise I am likewise stumped...

**Comment by mrocklin** [comment]
Is there a sequence of steps I can do to reproduce your docker setup?  I am not very adept at docker, so baby steps are encouraged.

**Comment by nfaggian** [comment]
I will prepare a repository on github to test this out and let you know.

Thanks for the help so far.

**Comment by nfaggian** [comment]
OK - Matthew, please refer to this repo:

     https://github.com/nfaggian/distributed-docker

If you follow the readme you should end up with an environment that shows how things have gone wrong...

**Comment by mrocklin** [comment]
```
mrocklin@workstation:~/workspace/distributed-docker/environment$ docker-compose up
WARNING: Please be aware that .yml is the expected extension in most cases, and using .yaml can cause compatibility issues in future.

Building scheduler
Step 0 : FROM centos:7
 ---> eeb3a076a0be
Step 1 : RUN yum -y update &&     yum -y install wget bzip2 git &&     yum clean all
 ---> Using cache
 ---> 7242008c2ea4
Step 2 : ADD environment.yml /opt
ERROR: Service 'scheduler' failed to build: stat /var/lib/docker/aufs/mnt/ae9cd1fb82d65a1be7b2664ffeee34a22435918edc7b9e5086e123995c341356/opt/environment.yml: not a directory
```

**Comment by nfaggian** [comment]
Wow.. I will have a look when I get to work

**Comment by nfaggian** [comment]
What does your "docker info" look like? could you have run out of disk?

**Comment by mrocklin** [comment]
```
mrocklin@workstation:~$ docker info
Error response from daemon: client and server don't have same version (client : 1.21, server: 1.18)
mrocklin@workstation:~$ sudo docker info
[sudo] password for mrocklin: 
Containers: 64
Images: 185
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 313
 Dirperm1 Supported: false
Execution Driver: native-0.2
Kernel Version: 3.13.0-65-generic
Operating System: Ubuntu 14.04.4 LTS
CPUs: 8
Total Memory: 15.55 GiB
Name: workstation
ID: GJ7Z:M7LL:4XJP:PUF7:FDDE:2TXR:5BWV:DK5G:LSGN:MCIF:U2VZ:CRYG
WARNING: No swap limit support
```

It's very possible that this is an environment problem on my end.  Feel free to recommend a standard way to install/run docker.

**Comment by nfaggian** [comment]
This is a screen grab I get from starting up the web view with the console open:

![image](https://cloud.githubusercontent.com/assets/377869/14727626/4b05199a-0870-11e6-970e-f5637cf146e5.png)

This is my docker info (older I guess):

```
[nfaggian@firefly ~]$ docker info
Containers: 20
Images: 83
Server Version: 1.9.1
Storage Driver: devicemapper
 Pool Name: docker-253:1-4325387-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: 
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 9.682 GB
 Data Space Total: 107.4 GB
 Data Space Available: 47.42 GB
 Metadata Space Used: 8.376 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.139 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /work/docker/devicemapper/devicemapper/data
 Metadata loop file: /work/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93 (2015-01-30)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.13-100.fc21.x86_64
Operating System: Fedora 21 (Twenty One)
CPUs: 8
Total Memory: 31.31 GiB
Name: firefly
ID: 24WL:RJHQ:J7PS:5FQU:5AHX:C4EL:D3FQ:BBMM:DI7D:FG32:BBSH:TTPC
[nfaggian@firefly ~]$ 
````

**Comment by nfaggian** [comment]
OK -- I feel silly, it seems to work now - Matthew I hope this hasn't caused you too much pain/time:

![image](https://cloud.githubusercontent.com/assets/377869/14727687/b677b7b4-0870-11e6-81b8-af1b4700864c.png)

**Comment by nfaggian** [comment]
I think the docker approach might be good to work through problems, maybe worth cleaning up what I have in "docker-distributed" for a test bed.

I am no docker expert ... probably worth getting someone else to cast a sensible eye over it.

**Comment by nfaggian** [comment]
OK - it seems to work fail I repeat this process on a remote PC - i.e. not my local desktop but a server I can spin up elsewhere on the network. Maybe a localhost thing...

**Comment by mrocklin** [comment]
So, to make sure I understand.  Things work when the browser and the docker container on the same physical machine but don't work when the browser is accessing the docker container on another machine?  

My first guess is that the name you're using to access the website isn't being listed properly under the `--host` keyword.  Can you verify that this is happening?

**Comment by nfaggian** [comment]
Hi Matthew - I will have a chance to look at this later today. But I believe your statement is correct.

**Comment by nfaggian** [comment]
Matthew, think it is safe to close this issue. Pin it down as my crazy working environment.

**Comment by mrocklin** [comment]
Alright.  I hope you're able to get the Web UI working.  I find it handy.  Please reopen if there is more I can do to help here.
