### ISSUE TITLE
dask futures break for msgpack 1.0

### ISSUE THREAD

**Issue by pfpt-jeremyv2** [dask/distributed#3583]
I had a Dask job which ran fine until recently. I was able to figure out that the behavior changed as a result of using a new version of `msgpack`.

It works fine with `msgpack==0.6.2` (which is what I had in my old Docker images) but breaks when I build newer images with `msgpack==1.0.0`. 

Stack trace:

```
distributed.scheduler - INFO - Unexpected worker completed task, likely due to work stealing.  Expected: tcp://100.64.204.169:42165, Got: tcp://100.64.29.7:46145, Key: process_report-2eac52bfd0e193dbd2f6a7071f8cc46c
distributed.scheduler - INFO - Unexpected worker completed task, likely due to work stealing.  Expected: tcp://100.64.203.25:45443, Got: tcp://100.64.29.7:46145, Key: process_report-59ead00e4881c928da0f5328f98efdd6
distributed.scheduler - INFO - Unexpected worker completed task, likely due to work stealing.  Expected: tcp://100.64.203.25:45443, Got: tcp://100.64.29.7:46145, Key: process_report-84491aae62ebee9b48f9b63d4114cb73
distributed.utils - ERROR - 'process_report-b24be718adb3d6a74ab2b09e0b0722ea'
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/distributed/utils.py", line 662, in log_errors
    yield
  File "/opt/conda/lib/python3.7/site-packages/distributed/scheduler.py", line 1498, in add_worker
    typename=types[key],
KeyError: 'process_report-b24be718adb3d6a74ab2b09e0b0722ea'
distributed.core - ERROR - 'process_report-b24be718adb3d6a74ab2b09e0b0722ea'
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/distributed/core.py", line 403, in handle_comm
    result = await result
  File "/opt/conda/lib/python3.7/site-packages/distributed/scheduler.py", line 1498, in add_worker
    typename=types[key],
KeyError: 'process_report-b24be718adb3d6a74ab2b09e0b0722ea'
distributed.scheduler - INFO - Remove worker tcp://100.64.29.7:46145
distributed.core - INFO - Removing comms to tcp://100.64.29.7:46145
distributed.scheduler - INFO - Unexpected worker completed task, likely due to work stealing.  Expected: tcp://100.64.32.69:35235, Got: tcp://100.64.214.198:33749, Key: process_report-562edd94942c6cd038df04db2108824e
distributed.protocol.core - CRITICAL - Failed to deserialize
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/distributed/protocol/core.py", line 106, in loads
    header = msgpack.loads(header, use_list=False, **msgpack_opts)
  File "msgpack/_unpacker.pyx", line 195, in msgpack._cmsgpack.unpackb
ValueError: tuple is not allowed for map key
distributed.utils_comm - INFO - Got an unexpected error while collecting from workers: tuple is not allowed for map key
distributed.scheduler - INFO - Remove worker tcp://100.64.203.25:45443
distributed.core - INFO - Removing comms to tcp://100.64.203.25:45443
distributed.scheduler - ERROR - Workers don't have promised key: ['tcp://100.64.203.25:45443'], process_report-130f564bbf149ca367974a121fa64cce
NoneType: None
distributed.client - WARNING - Couldn't gather 1 keys, rescheduling {'process_report-130f564bbf149ca367974a121fa64cce': ('tcp://100.64.203.25:45443',)}
distributed.protocol.core - CRITICAL - Failed to deserialize
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/distributed/protocol/core.py", line 106, in loads
    header = msgpack.loads(header, use_list=False, **msgpack_opts)
  File "msgpack/_unpacker.pyx", line 195, in msgpack._cmsgpack.unpackb
ValueError: tuple is not allowed for map key
distributed.utils - ERROR - tuple is not allowed for map key
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/distributed/utils.py", line 662, in log_errors
    yield
  File "/opt/conda/lib/python3.7/site-packages/distributed/client.py", line 1145, in _handle_report
    msgs = await self.scheduler_comm.comm.read()
  File "/opt/conda/lib/python3.7/site-packages/distributed/comm/tcp.py", line 208, in read
    frames, deserialize=self.deserialize, deserializers=deserializers
  File "/opt/conda/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/opt/conda/lib/python3.7/site-packages/distributed/comm/utils.py", line 64, in from_frames
    res = yield offload(_from_frames)
  File "/opt/conda/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/opt/conda/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/opt/conda/lib/python3.7/site-packages/distributed/utils.py", line 1370, in offload
    return (yield _offload_executor.submit(fn, *args, **kwargs))
  File "/opt/conda/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/opt/conda/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/opt/conda/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/opt/conda/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/conda/lib/python3.7/site-packages/distributed/comm/utils.py", line 52, in _from_frames
    frames, deserialize=deserialize, deserializers=deserializers
  File "/opt/conda/lib/python3.7/site-packages/distributed/protocol/core.py", line 106, in loads
    header = msgpack.loads(header, use_list=False, **msgpack_opts)
  File "msgpack/_unpacker.pyx", line 195, in msgpack._cmsgpack.unpackb
ValueError: tuple is not allowed for map key
```

**Comment by mrocklin** [comment]
I believe that we fixed this in a recent release of the dask distributed
package.  Can you try updating?

**Comment by pfpt-jeremyv2** [comment]
Ahh, yeah I had tried updating `dask (2.12.0)` to see if it would resolve the problem but forgot to also update `distributed`. Let me do that real quick and see if the error persists.

**Comment by pfpt-jeremyv2** [comment]
Hmm, it looks like a different variant of the problem still persists.

```
distributed.scheduler - INFO - Unexpected worker completed task, likely due to work stealing.  Expected: <Worker 'tcp://100.64.2.169:34875', name: tcp://100.64.2.169:34875, memory: 0, processing: 590>, Got: <Worker 'tcp://100.64.42.169:38379', name: tcp://100.64.42.169:38379, memory: 0, processing: 210>, Key: process_report-33a79d6f8a86dd502087dd5c0bc683e7
distributed.scheduler - ERROR - tuple indices must be integers or slices, not str
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/distributed/scheduler.py", line 4082, in transition_processing_memory
    for startstop in startstops
  File "/opt/conda/lib/python3.7/site-packages/distributed/scheduler.py", line 4083, in <listcomp>
    if startstop["action"] == "compute"
TypeError: tuple indices must be integers or slices, not str
distributed.scheduler - ERROR - Error transitioning 'process_report-c2c15200241cff73ad5da0a28c4c7e87' from 'processing' to 'memory'
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/distributed/scheduler.py", line 4607, in transition
    recommendations = func(key, *args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/distributed/scheduler.py", line 4082, in transition_processing_memory
    for startstop in startstops
  File "/opt/conda/lib/python3.7/site-packages/distributed/scheduler.py", line 4083, in <listcomp>
    if startstop["action"] == "compute"
TypeError: tuple indices must be integers or slices, not str
distributed.core - ERROR - tuple indices must be integers or slices, not str
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/distributed/core.py", line 473, in handle_stream
    handler(**merge(extra, msg))
  File "/opt/conda/lib/python3.7/site-packages/distributed/scheduler.py", line 2598, in handle_task_finished
    r = self.stimulus_task_finished(key=key, worker=worker, **msg)
  File "/opt/conda/lib/python3.7/site-packages/distributed/scheduler.py", line 2016, in stimulus_task_finished
    recommendations = self.transition(key, "memory", worker=worker, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/distributed/scheduler.py", line 4607, in transition
    recommendations = func(key, *args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/distributed/scheduler.py", line 4082, in transition_processing_memory
    for startstop in startstops
  File "/opt/conda/lib/python3.7/site-packages/distributed/scheduler.py", line 4083, in <listcomp>
    if startstop["action"] == "compute"
TypeError: tuple indices must be integers or slices, not str
distributed.scheduler - INFO - Remove worker <Worker 'tcp://100.64.2.169:34875', name: tcp://100.64.2.169:34875, memory: 0, processing: 605>
distributed.core - INFO - Removing comms to tcp://100.64.2.169:34875
distributed.utils - ERROR - tuple indices must be integers or slices, not str
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/distributed/utils.py", line 665, in log_errors
    yield
  File "/opt/conda/lib/python3.7/site-packages/distributed/scheduler.py", line 1740, in add_worker
    await self.handle_worker(comm=comm, worker=address)
  File "/opt/conda/lib/python3.7/site-packages/distributed/scheduler.py", line 2695, in handle_worker
    await self.handle_stream(comm=comm, extra={"worker": worker})
  File "/opt/conda/lib/python3.7/site-packages/distributed/core.py", line 473, in handle_stream
    handler(**merge(extra, msg))
  File "/opt/conda/lib/python3.7/site-packages/distributed/scheduler.py", line 2598, in handle_task_finished
    r = self.stimulus_task_finished(key=key, worker=worker, **msg)
  File "/opt/conda/lib/python3.7/site-packages/distributed/scheduler.py", line 2016, in stimulus_task_finished
    recommendations = self.transition(key, "memory", worker=worker, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/distributed/scheduler.py", line 4607, in transition
    recommendations = func(key, *args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/distributed/scheduler.py", line 4082, in transition_processing_memory
    for startstop in startstops
  File "/opt/conda/lib/python3.7/site-packages/distributed/scheduler.py", line 4083, in <listcomp>
    if startstop["action"] == "compute"
TypeError: tuple indices must be integers or slices, not str
distributed.core - ERROR - tuple indices must be integers or slices, not str
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/distributed/core.py", line 412, in handle_comm
    result = await result
  File "/opt/conda/lib/python3.7/site-packages/distributed/scheduler.py", line 1740, in add_worker
    await self.handle_worker(comm=comm, worker=address)
  File "/opt/conda/lib/python3.7/site-packages/distributed/scheduler.py", line 2695, in handle_worker
    await self.handle_stream(comm=comm, extra={"worker": worker})
  File "/opt/conda/lib/python3.7/site-packages/distributed/core.py", line 473, in handle_stream
    handler(**merge(extra, msg))
  File "/opt/conda/lib/python3.7/site-packages/distributed/scheduler.py", line 2598, in handle_task_finished
    r = self.stimulus_task_finished(key=key, worker=worker, **msg)
  File "/opt/conda/lib/python3.7/site-packages/distributed/scheduler.py", line 2016, in stimulus_task_finished
    recommendations = self.transition(key, "memory", worker=worker, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/distributed/scheduler.py", line 4607, in transition
    recommendations = func(key, *args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/distributed/scheduler.py", line 4082, in transition_processing_memory
    for startstop in startstops
  File "/opt/conda/lib/python3.7/site-packages/distributed/scheduler.py", line 4083, in <listcomp>
    if startstop["action"] == "compute"
```

**Comment by mrocklin** [comment]
Can you verify that all of your scheduler/workers have been updated?  What
happens if you call client.get_versions(check=True) ?

**Comment by pfpt-jeremyv2** [comment]
@mrocklin aha! That was the problem (workers were still using an older version). Thanks for the help :)
