### ISSUE TITLE
AssertionError: Status.created

### ISSUE THREAD

**Issue by tekumara** [dask/distributed#6183]
**What happened**:

All tasks complete successfully but during shutdown the client throws:
```
[2022-04-23 09:47:01+0000] ERROR - prefect.CloudFlowRunner | Unexpected error: AssertionError(<Status.created: 'created'>)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/prefect/engine/runner.py", line 48, in inner
    new_state = method(self, state, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/prefect/engine/flow_runner.py", line 661, in get_flow_run_state
    assert isinstance(final_states, dict)
  File "/usr/local/lib/python3.9/contextlib.py", line 126, in __exit__
    next(self.gen)
  File "/usr/local/lib/python3.9/site-packages/prefect/executors/dask.py", line 270, in start
    self._post_start_yield()
  File "/usr/local/lib/python3.9/site-packages/distributed/deploy/spec.py", line 435, in __exit__
    super().__exit__(typ, value, traceback)
  File "/usr/local/lib/python3.9/site-packages/distributed/deploy/cluster.py", line 466, in __exit__
    return self.sync(self.__aexit__, typ, value, traceback)
  File "/usr/local/lib/python3.9/site-packages/distributed/utils.py", line 309, in sync
    return sync(
  File "/usr/local/lib/python3.9/site-packages/distributed/utils.py", line 376, in sync
    raise exc.with_traceback(tb)
  File "/usr/local/lib/python3.9/site-packages/distributed/utils.py", line 349, in f
    result = yield future
  File "/usr/local/lib/python3.9/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/usr/local/lib/python3.9/site-packages/distributed/deploy/cluster.py", line 475, in __aexit__
    await f
  File "/usr/local/lib/python3.9/site-packages/distributed/deploy/spec.py", line 419, in _close
    assert w.status == Status.closed, w.status
AssertionError: Status.created
```

Final logs from the dask scheduler and last worker:
```
dask-root-af52d060-bd827h dask-worker 2022-04-23 09:30:58,539 - distributed.active_memory_manager - INFO - Retiring worker tcp://10.144.175.79:43489; 1 keys are being moved away.
dask-root-af52d060-bd827h dask-worker 2022-04-23 09:30:58,550 - distributed.scheduler - INFO - Closing worker tcp://10.144.175.79:43489
dask-root-af52d060-bd827h dask-worker 2022-04-23 09:30:58,550 - distributed.scheduler - INFO - Remove worker <WorkerState 'tcp://10.144.175.79:43489', name: 32, status: closing_gracefully, memory: 1, processing: 0>
dask-root-af52d060-bd827h dask-worker 2022-04-23 09:30:58,550 - distributed.core - INFO - Removing comms to tcp://10.144.175.79:43489
dask-root-af52d060-bd827h dask-worker 2022-04-23 09:30:58,551 - distributed.scheduler - INFO - Retired worker tcp://10.144.175.79:43489
dask-root-af52d060-bcl2v4 dask-worker 2022-04-23 07:27:48,127 - distributed.worker - INFO - -------------------------------------------------
dask-root-af52d060-bcl2v4 dask-worker 2022-04-23 07:27:48,333 - distributed.worker - INFO -         Registered to: tcp://dask-root-af52d060-b.namespace:8786
dask-root-af52d060-bcl2v4 dask-worker 2022-04-23 07:27:48,334 - distributed.worker - INFO - -------------------------------------------------
dask-root-af52d060-bcl2v4 dask-worker 2022-04-23 07:27:48,334 - distributed.core - INFO - Starting established connection
dask-root-af52d060-bcl2v4 dask-worker [2022-04-23 07:27:49+0000] INFO - prefect.CloudTaskRunner | Task 'predict[24]': Starting task run...
dask-root-af52d060-bcl2v4 dask-worker [2022-04-23 09:46:59+0000] INFO - prefect.CloudTaskRunner | Task 'predict[24]': Finished task run for task with final state: 'Success'
dask-root-af52d060-bcl2v4 dask-worker [2022-04-23 09:46:59+0000] INFO - prefect.CloudTaskRunner | Task 'log_totals': Starting task run...
dask-root-af52d060-bcl2v4 dask-worker [2022-04-23 09:46:59+0000] INFO - prefect.CloudTaskRunner | Task 'log_totals': Finished task run for task with final state: 'Success'
dask-root-af52d060-bd827h dask-worker 2022-04-23 09:46:59,863 - distributed.scheduler - INFO - Remove client Client-d21a4767-c2d6-11ec-8001-d20bcc1cc2b0
dask-root-af52d060-bd827h dask-worker 2022-04-23 09:46:59,864 - distributed.scheduler - INFO - Remove client Client-d21a4767-c2d6-11ec-8001-d20bcc1cc2b0
dask-root-af52d060-bd827h dask-worker 2022-04-23 09:46:59,864 - distributed.scheduler - INFO - Close client connection: Client-d21a4767-c2d6-11ec-8001-d20bcc1cc2b0
dask-root-af52d060-bcl2v4 dask-worker 2022-04-23 09:46:59,899 - distributed.worker - INFO - Stopping worker at tcp://10.144.161.29:34669
dask-root-af52d060-bd827h dask-worker 2022-04-23 09:46:59,896 - distributed.scheduler - INFO - Scheduler closing...
dask-root-af52d060-bd827h dask-worker 2022-04-23 09:46:59,902 - distributed.scheduler - INFO - Remove worker <WorkerState 'tcp://10.144.161.29:34669', name: 31, status: closing, memory: 0, processing: 0>
dask-root-af52d060-bd827h dask-worker 2022-04-23 09:46:59,902 - distributed.core - INFO - Removing comms to tcp://10.144.161.29:34669
dask-root-af52d060-bd827h dask-worker 2022-04-23 09:46:59,902 - distributed.scheduler - INFO - Lost all workers
dask-root-af52d060-bcl2v4 dask-worker 2022-04-23 09:46:59,902 - distributed.nanny - INFO - Worker closed
dask-root-af52d060-bd827h dask-worker 2022-04-23 09:46:59,949 - distributed.scheduler - INFO - Scheduler closing all comms
dask-root-af52d060-bcl2v4 dask-worker 2022-04-23 09:46:59,904 - distributed.dask_worker - INFO - Exiting on signal 15
dask-root-af52d060-bcl2v4 dask-worker 2022-04-23 09:46:59,904 - distributed.nanny - INFO - Closing Nanny at 'tcp://10.144.161.29:43057'
dask-root-af52d060-bd827h dask-worker 2022-04-23 09:47:00,966 - distributed.scheduler - INFO - End scheduler at 'tcp://10.144.167.44:8786'
dask-root-af52d060-bcl2v4 dask-worker 2022-04-23 09:47:01,529 - distributed.nanny - WARNING - Worker process still alive after 1.5999990463256837 seconds, killing
dask-root-af52d060-bcl2v4 dask-worker 2022-04-23 09:47:01,530 - distributed.dask_worker - INFO - End worker
dask-root-af52d060-bcl2v4 dask-worker 2022-04-23 09:47:01,530 - distributed.process - INFO - reaping stray process <SpawnProcess name='Dask Worker process (from Nanny)' pid=58 parent=1 started daemon>
dask-root-af52d060-bcl2v4 dask-worker Exception in thread AsyncProcess Dask Worker process (from Nanny) watch process join:
dask-root-af52d060-bcl2v4 dask-worker Traceback (most recent call last):
dask-root-af52d060-bcl2v4 dask-worker Fatal Python error: _enter_buffered_busy: could not acquire lock for <_io.BufferedWriter name='<stderr>'> at interpreter shutdown, possibly due to daemon threads
dask-root-af52d060-bcl2v4 dask-worker Python runtime state: finalizing (tstate=0x564090dbe750)
dask-root-af52d060-bcl2v4 dask-worker
dask-root-af52d060-bcl2v4 dask-worker Current thread 0x00007fa32fab7740 (most recent call first):
dask-root-af52d060-bcl2v4 dask-worker <no Python frame>
```

**What you expected to happen**:

No exception during shutdown.

**Environment**:

Dask on Kuberenetes

- Dask version: dask 2022.4.1, dask-kubernetes 2021.10.0
- Python version: 3.9.12
- Operating System: Debian GNU/Linux 11 (bullseye)
- Install method (conda, pip, source): pip

**Comment by madkinsz** [comment]
Feel free to ping me if I should look into anything on our end.

**Comment by mrocklin** [comment]
cc @jacobtomlinson if you or someone around you has a chance to take a look. 

@tekumara any chance that you have adaptive turned on?  

it looks like a new worker arrives just as we're closing down.  We should be robust to this.  I'm just curious how the situation arose in the first place.

**Comment by tekumara** [comment]
Thank you for looking into this. Yes adaptive scaling is on. It's happened a couple of times now.

**Comment by jacobtomlinson** [comment]
@tekumara could you share a small reproducible example so I can dig into this?

**Comment by tekumara** [comment]
I'm not sure how to reliably reproduce this yet. It doesn't always happen. If I can identity a pattern over time, or some way to reproduce it I'll let you know.

**Comment by fjetter** [comment]
Might have been fixed by https://github.com/dask/distributed/pull/5910

**Comment by tekumara** [comment]
Thanks @fjetter we are still encountering this using dask 2022.6.0

**Comment by fjetter** [comment]
@tekumara do you have a more recent traceback?

**Comment by tekumara** [comment]
@fjetter:
```
Unexpected error: AssertionError(<Status.created: 'created'>)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/prefect/engine/runner.py", line 48, in inner
    new_state = method(self, state, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/prefect/engine/flow_runner.py", line 661, in get_flow_run_state
    assert isinstance(final_states, dict)
  File "/usr/local/lib/python3.9/contextlib.py", line 126, in __exit__
    next(self.gen)
  File "/usr/local/lib/python3.9/site-packages/prefect/executors/dask.py", line 258, in start
    self._post_start_yield()
  File "/usr/local/lib/python3.9/site-packages/distributed/deploy/spec.py", line 441, in __exit__
    super().__exit__(exc_type, exc_value, traceback)
  File "/usr/local/lib/python3.9/site-packages/distributed/deploy/cluster.py", line 469, in __exit__
    return self.sync(self.__aexit__, exc_type, exc_value, traceback)
  File "/usr/local/lib/python3.9/site-packages/distributed/utils.py", line 320, in sync
    return sync(
  File "/usr/local/lib/python3.9/site-packages/distributed/utils.py", line 387, in sync
    raise exc.with_traceback(tb)
  File "/usr/local/lib/python3.9/site-packages/distributed/utils.py", line 360, in f
    result = yield future
  File "/usr/local/lib/python3.9/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/usr/local/lib/python3.9/site-packages/distributed/deploy/cluster.py", line 478, in __aexit__
    await f
  File "/usr/local/lib/python3.9/site-packages/distributed/deploy/spec.py", line 421, in _close
    assert w.status in {
AssertionError: Status.created
```

**Comment by tekumara** [comment]
It appears to occur more often when we spin up multiple ephemeral adaptive dask clusters at the same time... if that helps identify the cause?

**Comment by tekumara** [comment]
It appears to occur more often when we spin up multiple ephemeral adaptive dask clusters at the same time within the same kubernetes namespace... if that helps identify the cause?

**Comment by fjetter** [comment]
My best guess is that this is connected to https://github.com/dask/distributed/issues/5919 but from what I understand your problem has to be linked to the usage of another library as well, likely prefect. The only place where this `Status.created` is even set is the [`ProcessInterface`](https://github.com/dask/distributed/blob/main/distributed/deploy/spec.py#L56) which `dask.distributed` is not even using anywhere.

@madkinsz how is prefect starting workers?

**Comment by tekumara** [comment]
Yep this is an ephemeral KubeCluster. We use prefect's DaskExecutor:
```python
    flow.executor = DaskExecutor(
        cluster_class=lambda: configure_dask_cluster(image, settings, commit_url),
        adapt_kwargs={"minimum": 1, "maximum": max_pods}
    )
```

```python
def configure_dask_cluster(image: str, settings: DaskSettings, commit_url: str) -> KubeCluster:
    service_account_name = f"{settings.project_name}-flows-svc"
    worker_pod = dask_pod_spec(
        image,
        service_account_name,
        settings.worker_cpu_request,
        settings.worker_cpu_limit,
        settings.worker_mem_request,
        settings.worker_mem_limit,
        commit_url)
    scheduler_pod = dask_pod_spec(
        image,
        service_account_name,
        settings.scheduler_cpu_request,
        settings.scheduler_cpu_limit,
        settings.scheduler_mem_request,
        settings.scheduler_mem_limit,
        commit_url)

    # override default PodDisruptionBudget
    dask.config.update(dask.config.global_config, {
        'kubernetes': {
            'scheduler-pdb-template': {
                'spec': {
                    'minAvailable': 0
                }
            }
        }
    })

    return KubeCluster(pod_template=worker_pod, scheduler_pod_template=scheduler_pod)
```

**Comment by jacobtomlinson** [comment]
> I'm not sure how to reliably reproduce this yet. It doesn't always happen. If I can identity a pattern over time, or some way to reproduce it I'll let you know.

This will likely be challenging to track down, we will need a minimal reproducer that causes this to happen. 

I've tried launching a bunch of `KubeCluster` objects in the same namespace but haven't seen this come up yet.

```python
from dask_kubernetes import KubeCluster, make_pod_spec

pod_spec = make_pod_spec(image='ghcr.io/dask/dask:latest')

clusters = []
for _ in range(10):
    clusters.append(KubeCluster(pod_spec))
```

I'll leave this running a bit longer and try and create a whole bunch of `KubeCluster` objects in the same namespace, but we might need more info to figure this out.

Perhaps you could share the `settings` values or anything else you might think is relevant?
