### ISSUE TITLE
py.test distributed fails with "DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`"

### ISSUE THREAD

**Issue by jaceklaskowski** [dask/distributed#7422]
`py.test distributed --verbose` fails with the following errors on `2022.12.1` branch.

```text
ERROR distributed/dashboard/tests/test_components.py - DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
ERROR distributed/dashboard/tests/test_scheduler_bokeh.py - DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
ERROR distributed/dashboard/tests/test_worker_bokeh.py - DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
```

## Steps to reproduce

```console
$ git branch --show-current
2022.12.1

$ conda env create --file continuous_integration/environment-3.10.yaml
...
Successfully installed dask-2022.12.1+2.g0570a08a fsspec-2022.11.0+13.g0974514 keras-2.11.0 s3fs-2022.11.0+4.g5917684
done

$ conda activate dask-distributed

$ python --version
Python 3.10.8

$ python -m pip install -e .
...
Successfully installed dask-2022.11.1 distributed-2022.11.1+1.g856d403b

$ py.test distributed --verbose
...
ERROR distributed/dashboard/tests/test_components.py - DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
ERROR distributed/dashboard/tests/test_scheduler_bokeh.py - DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
ERROR distributed/dashboard/tests/test_worker_bokeh.py - DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
```

**Comment by mrocklin** [comment]
Thank you for raising this @jaceklaskowski .  It looks like this is coming from upstream in Bokeh

```python-traceback
____________________ ERROR collecting distributed/dashboard/tests/test_worker_bokeh.py ____________________
distributed/dashboard/tests/test_worker_bokeh.py:15: in <module>
    from distributed.dashboard.components.worker import (
distributed/dashboard/components/__init__.py:5: in <module>
    from bokeh.core.properties import without_property_validation
../../mambaforge/envs/dask-distributed/lib/python3.10/site-packages/bokeh/core/properties.py:273: in <module>
    from .property.auto import Auto; Auto
../../mambaforge/envs/dask-distributed/lib/python3.10/site-packages/bokeh/core/property/auto.py:24: in <module>
    from .enum import Enum
../../mambaforge/envs/dask-distributed/lib/python3.10/site-packages/bokeh/core/property/enum.py:27: in <module>
    from .primitive import String
../../mambaforge/envs/dask-distributed/lib/python3.10/site-packages/bokeh/core/property/primitive.py:37: in <module>
    bokeh_bool_types += (np.bool8,)
../../mambaforge/envs/dask-distributed/lib/python3.10/site-packages/numpy/__init__.py:260: in __getattr__
    warnings.warn(msg, DeprecationWarning, stacklevel=2)
```

cc'ing @bryevdv 

I've raised upstream at https://github.com/bokeh/bokeh/issues/12689

**Comment by mrocklin** [comment]
And locally fixed in https://github.com/dask/distributed/pull/7423 temporarily

**Comment by jaceklaskowski** [comment]
Looks like it has not been fixed yet. I'm on the recent `2023.2.0` tag and the ERRORs are still there.

```
$ git branch --show-current
2023.2.0

(dask-distributed) ╭─ ~/dev/oss/dask/distributed ‹heads/2023.2.0›
╰─$ py.test distributed --verbose
================================================================= test session starts =================================================================
platform darwin -- Python 3.10.9, pytest-7.2.1, pluggy-1.0.0 -- /usr/local/Caskroom/miniconda/base/envs/dask-distributed/bin/python3.10
cachedir: .pytest_cache
rootdir: /Users/jacek/dev/oss/dask/distributed, configfile: setup.cfg
plugins: rerunfailures-11.1, timeout-2.1.0, cov-4.0.0, repeat-0.9.1
timeout: 300.0s
timeout method: thread
timeout func_only: False
collected 3143 items / 3 errors / 10 skipped
...
ERROR distributed/dashboard/tests/test_components.py - DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
ERROR distributed/dashboard/tests/test_scheduler_bokeh.py - DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
ERROR distributed/dashboard/tests/test_worker_bokeh.py - DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 3 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
=========================================================== 10 skipped, 3 errors in 22.75s ============================================================
```

**Comment by jrbourbeau** [comment]
Thanks @jaceklaskowski. I'm not able to reproduce on the `2023.2.0` release

```
distributed on  HEAD (63ae1db) [$] via 🐍 v3.10.6 via 🅒 distributed took 1m13s
❯ mamba list numpy
# packages in environment at /Users/james/mambaforge/envs/distributed:
#
# Name                    Version                   Build  Channel
numpy                     1.24.2                   pypi_0    pypi
numpydoc                  1.4.0                    pypi_0    pypi
(distributed)
distributed on  HEAD (63ae1db) [$] via 🐍 v3.10.6 via 🅒 distributed took 3s
❯ pytest distributed/dashboard/tests/test_components.py
===================================================================== test session starts =====================================================================
platform darwin -- Python 3.10.6, pytest-7.1.2, pluggy-1.0.0 -- /Users/james/mambaforge/envs/distributed/bin/python
cachedir: .pytest_cache
rootdir: /Users/james/projects/dask/distributed, configfile: setup.cfg
plugins: anyio-3.6.1, xdist-2.5.0, forked-1.4.0, timeout-2.1.0, rerunfailures-10.2, repeat-0.9.1, cov-3.0.0
timeout: 300.0s
timeout method: thread
timeout func_only: False
collected 4 items

distributed/dashboard/tests/test_components.py::test_basic[Processing] PASSED                                                                           [ 25%]
distributed/dashboard/tests/test_components.py::test_profile_plot PASSED                                                                                [ 50%]
distributed/dashboard/tests/test_components.py::test_profile_time_plot PASSED                                                                           [ 75%]
distributed/dashboard/tests/test_components.py::test_profile_time_plot_disabled PASSED                                                                  [100%]

==================================================================== slowest 20 durations =====================================================================
0.81s call     distributed/dashboard/tests/test_components.py::test_profile_plot
0.44s call     distributed/dashboard/tests/test_components.py::test_profile_time_plot
0.17s call     distributed/dashboard/tests/test_components.py::test_profile_time_plot_disabled
0.01s call     distributed/dashboard/tests/test_components.py::test_basic[Processing]

(8 durations < 0.005s hidden.  Use -vv to show these durations.)
====================================================================== 4 passed in 3.06s ======================================================================
```

Also, grepping through the `distributed` codebase, there are no references to `np.bool8` in code. Could you post the full tracebacks?

**Comment by bryevdv** [comment]
@mrocklin recently made a PR to remove `np.bool8` from Bokeh on `branch-3.1` but version 3.1 has not yet been released. It should be out later this month. I would not expect any future 3.0.x releases, so 3.1 will be the first release that has the change.

**Comment by jrbourbeau** [comment]
Ah, great. Thanks for clarifying @bryevdv!

**Comment by jaceklaskowski** [comment]
@jrbourbeau I'm very very sorry for the noise. It was unintentional and a terrible mistake of mine. My git voodoo didn't work out very well this time and I simply `git fetch` not `git pull` so no changes were pulled from the upstream repo (that got me "pinned" to the older version of dask). Sorry about that.

Yet I ran into another issue but I'll report it as a separate build issue. `np.bool8` is no longer a build issue.

Thanks a lot for your patience! ❤️ 

BTW, What's your `PS1` setup? I like the prompt (`distributed on  HEAD (63ae1db) [$] via 🐍 v3.10.6 via 🅒 distributed took 1m13s`)
